from titik import *
def main():
    BacaPoint("1")
    BacaPoint("2")
    BacaPoint("3")
    BacaPoint("4")
    print("GetAbsis P1              : {:.0f}".format(GetAbsis("1")))
    print("GetOrdinat P1            : {:.0f}".format(GetOrdinat("1")))
    print("P4 setelah diset (4, 4)  : ({}, {})".format(SetAbsis(4,"4"),SetOrdinat(4,"4")))
    print("P5 setelah diset (-2, 2) : ({}, {})".format(SetAbsis(-2,"5"),SetOrdinat(2,"5")))
    print("Tulis P5 = P1+P2         : ({})".format(AddP(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("Tulis P5 = P1-P2         : ({})".format(MinP(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("Tulis P5 = P1.P2         : ({})".format(MulDot(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("Equal   P1 P2            ? {}".format(IsEqual(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("~Equal   P1 P2           ? {}".format(IsNotEqual(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("Less    P1 P2            ? {}".format(IsLess(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("Greate  P1 P2            ? {}".format(IsGreater(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("Origin  P1               ? {}".format(IsOrigin(GetAbsis("1"),GetOrdinat("1"))))
    print("IsOnSbX P1               ? {}".format(IsOnSbX(GetAbsis("1"))))
    print("IsOnSbY P1               ? {}".format(IsOnSbX(GetOrdinat("1"))))
    print("P1 Kuadran Ke            : {}".format(Kuadran(GetAbsis("1"),GetOrdinat("1"))))
    print("P2 Kuadran Ke            : {}".format(Kuadran(GetAbsis("2"),GetOrdinat("2"))))
    print("P3 Kuadran Ke            : {}".format(Kuadran(GetAbsis("3"),GetOrdinat("3"))))
    print("P4 Kuadran Ke            : {} <-Sudah diset diatas dengan 4,4".format(Kuadran(GetAbsis("4"),GetOrdinat("4"))))
    print("Next P1                  : ({}, {})".format(NextX(GetAbsis("1"),"1"),NextY(GetOrdinat("1"),"1")))
    print("Next P2                  : ({}, {})".format(NextX(GetAbsis("2"),"2"),NextY(GetOrdinat("2"),"2")))
    print("PlusDelta P3 (2, 2)      : ({})".format(PlusDelta(GetAbsis("3"),GetOrdinat("3"),2,2,"3")))
    print("Mirror P4 SbX            : ({})".format(MirrorOf(GetAbsis("4"),GetOrdinat("4"),"SbX","4")))
    print("Geser P1 (2, 3)          : ({})".format(Geser(GetAbsis("1"),GetOrdinat("1"),2,3,"1")))
    print("Mirror P2 SbX            : ({})".format(MirrorOf(GetAbsis("2"),GetOrdinat("2"),"SbX","2")))
    print("Mirror P3 SbY            : ({})".format(MirrorOf(GetAbsis("3"),GetOrdinat("3"),"SbY","3")))
    print("Tulis P1                 : ({}, {})".format(GetAbsis("1"),GetOrdinat("1")))
    print("Jarak P1 dr (0, 0)       : {}".format(JarakPst(GetAbsis("1"),GetOrdinat("1"))))
    print("Jarak P1 P2              : {}".format(Jarak2T(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
    print("P1 sblm rot 30 CCW       : ({}, {})".format(GetAbsis("1"),GetOrdinat("1")))
    print("P1 stlh rot 30 CCW       : ({})".format(Putar(GetAbsis("1"),GetOrdinat("1"),30)))
    print("P1 stlh rot -30 CCW      : ({})".format(Putar(GetAbsis("1"),GetOrdinat("1"),-30)))
    print("Koord 2 titik P1 dan P2  : ({})".format(AddP(GetAbsis("1"),GetOrdinat("1"),GetAbsis("2"),GetOrdinat("2"))))
if __name__ == "__main__":
    main()
