from matematika import *
def main():
    a,b,x=Max2(2,5)
    print("Max2 --> {} atau {}                : {}".format(a,b,x))
    a,b,c,x=Max3(2,5,1)
    print("Max3 --> {} atau {} atau {}         : {}".format(a,b,c,x))
    a,b,c,d,x=Max4(7,2,5,1)
    print("Max4 --> {} atau {} atau {} atau {}  : {}".format(a,b,c,d,x))
    N,x=IsPrima(7)
    print("IsPrima {}                        : {}".format(N,x))
    N,x=IsPrima(17)
    print("IsPrima {}                       : {}".format(N,x))
    N,x=IsPrima(70)
    print("IsPrima {}                       : {}".format(N,x))
    n,m,fpb=FPB(36,48)
    print("FPB ({}, {})                     : {}".format(n,m,fpb))
    N,x=IsGanjil(93)
    print("IsGanjil {}                      : {}".format(N,x))
    N,x=IsGanjil(1324)
    print("IsGanjil {}                    : {}".format(N,x))
    basis,eksp,pangkat=Pangkat(2,8)
    print("Pangkat ({}, {})                   : {}".format(basis,eksp,pangkat))
    N,numb=NumOfPrima(15)
    print("NumOfPrima ({})                  : {}".format(N,numb))
    N,sumData=SumOfN(15)
    print("SumOfN ({})                      : {}".format(N,sumData))
    N,multiply=ProductOfN(15)
    print("ProductOfN ({})                  : {}".format(N,multiply))
    N,ave=AveSumOfN(15)
    print("ProductOfN ({})                  : {}".format(N,ave))
    N,ave=AveProdOfN(15)
    print("AveProdOfN ({})                  : {}".format(N,ave))
    C,f=C2F(72.50)
    print("{} C adalah {} F".format(C,f))
    F,c=F2C(13.50)
    print("{} F adalah {} C".format(F,c))
    C,r=C2R(72.50)
    print("{} C adalah {} R".format(C,r))
    R,c=R2C(22.50)
    print("{} R adalah {} C".format(R,c))
    C,k=K2C(72.50)
    print("{} C adalah {} K".format(C,k))
    K,c=C2K(172.50)
    print("{} K adalah {} C".format(K,c))
    R,f=R2F(72.50)
    print("{} R adalah {} F".format(R,f))
    F,r=F2R(62.50)
    print("{} F adalah {} R".format(F,r))
if __name__ == "__main__":
    main()
